# account info
account:
  DATA_CENTER: yul1
  DEFAULT_DIRECTORY: POOL_3fAZGWRVfLKuxe3
  LIBRARY_ID: GR_2fXBZYGAqiAoC3Q
  VERIFY: True

# project info
project:
  # Survey
  SURVEY_ID: SV_8iigy1iCkAhAFSe
  # message
  MESSAGE_ID: MS_bxyj8Z7vUXKLTZc
  # mailing_list
  MAILING_LIST_ID: CG_2XpNxso87o1O548
  TIMEZONE: America/Chicago
  MINUTES_EXPIRE: 60

MAILING_LISTS:

# default embedded data
embedded_data:
  # StartDate: '2024-03-16'
  SurveysScheduled: 0
  # TimeSlots: 800,1200,1600,2000
  # UseSMS: 1
  # DeleteUnsent: 0
  # NumDays: 0
  # ExpireMinutes: 60
  # LogData: '[{"action":"init"}]'
  # TimeZone: America/Chicago
 
